import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function ProjectCard({ name, description, url, thumbnail, accent = "#f0ede8" }) {
    const domain = (() => { try {
        return new URL(url).hostname.replace("www.", "");
    }
    catch {
        return url;
    } })();
    return (_jsx("a", { href: url, target: "_blank", rel: "noopener noreferrer", style: { textDecoration: "none", display: "block", height: "100%" }, children: _jsxs("div", { style: {
                background: "var(--card)", border: "1px solid var(--border)",
                borderRadius: "var(--radius)", height: "100%", overflow: "hidden",
                display: "flex", flexDirection: "column", cursor: "pointer",
                transition: "transform 0.15s ease, box-shadow 0.15s ease",
            }, onMouseEnter: (e) => { e.currentTarget.style.transform = "translateY(-1px)"; e.currentTarget.style.boxShadow = "0 4px 24px rgba(0,0,0,0.07)"; }, onMouseLeave: (e) => { e.currentTarget.style.transform = ""; e.currentTarget.style.boxShadow = ""; }, children: [_jsx("div", { style: { flex: 1, background: accent, overflow: "hidden", position: "relative", minHeight: 130 }, children: thumbnail ? (_jsx("img", { src: thumbnail, alt: name, style: { width: "100%", height: "100%", objectFit: "cover", objectPosition: "top" } })) : (_jsx("div", { style: { width: "100%", height: "100%", display: "flex", alignItems: "center", justifyContent: "center" }, children: _jsxs("div", { style: { width: "75%", background: "white", borderRadius: 8, overflow: "hidden", boxShadow: "0 2px 12px rgba(0,0,0,0.09)" }, children: [_jsxs("div", { style: { background: "#f5f4f1", padding: "7px 10px", display: "flex", alignItems: "center", gap: 5, borderBottom: "1px solid #e8e7e3" }, children: [["#ff5f57", "#febc2e", "#28c840"].map(c => _jsx("div", { style: { width: 8, height: 8, borderRadius: "50%", background: c } }, c)), _jsx("div", { style: { flex: 1, marginLeft: 6, background: "#ebe9e4", borderRadius: 4, height: 8 } })] }), _jsx("div", { style: { padding: "14px 12px" }, children: [["70%", "7px"], ["90%", "5px"], ["60%", "5px"]].map(([w, h], i) => (_jsx("div", { style: { height: h, background: i === 0 ? "#ebe9e4" : "#f0ede8", borderRadius: 3, marginBottom: i < 2 ? 6 : 0, width: w } }, i))) })] }) })) }), _jsxs("div", { style: { padding: "0.85rem 1rem", borderTop: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "space-between", flexShrink: 0 }, children: [_jsxs("div", { children: [_jsx("p", { style: { fontSize: "0.875rem", fontWeight: 500, lineHeight: 1.3 }, children: name }), _jsx("p", { style: { fontSize: "0.72rem", color: "var(--muted)", marginTop: 2 }, children: description })] }), _jsxs("div", { style: { display: "flex", alignItems: "center", gap: 4, flexShrink: 0, marginLeft: 8 }, children: [_jsx("span", { style: { fontSize: "0.68rem", color: "var(--muted)" }, children: domain }), _jsx("svg", { width: "11", height: "11", viewBox: "0 0 11 11", fill: "none", style: { opacity: 0.3 }, children: _jsx("path", { d: "M1.5 9.5L9.5 1.5M9.5 1.5H3.5M9.5 1.5v6", stroke: "var(--text)", strokeWidth: "1.5", strokeLinecap: "round", strokeLinejoin: "round" }) })] })] })] }) }));
}
